# ----------------------------------------------------------------------------------------------------
# Pipe to build an Azure Container App for multiple apps and environments
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environmentName
    type: string
    default: 'DEV'

  - name: pushToACR
    default: true
    type: boolean

  - name: deployUI
    default: true
    type: boolean
  - name: apiConfig
    type: object
    default: {}

# ----------------------------------------------------------------------------------------------------
stages:
- stage: BuildAll${{ parameters.environmentName }}Service
  displayName: Build All ${{ parameters.environmentName }}
  jobs:
    - template: templates/aca-build-all-template.yml
      parameters:
        serviceConnectionName: $(serviceConnectionName)
        environmentName: ${{ parameters.environmentName }}
        pushToACR: ${{ parameters.pushToACR }}

        uiAcrAppName: ${{ parameters.apiConfig.acrAppName }}
        uiProjectFolderName: ${{ parameters.apiConfig.projectFolderName }}
